# Generated by Django 5.1.1 on 2024-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
    ]
